---
# Source: victoria-metrics-k8s-stack/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-prometheus-node-exporter
  namespace: observability
  labels:
    helm.sh/chart: prometheus-node-exporter-4.27.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: vm
    app.kubernetes.io/version: "1.7.0"
    jobLabel: node-exporter
