---
# Source: victoria-metrics-k8s-stack/charts/grafana/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: victoria-metrics-stack-grafana-test
  labels:
    helm.sh/chart: grafana-6.59.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: victoria-metrics-stack
    app.kubernetes.io/version: "10.1.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
  namespace: observability
spec:
  serviceAccountName: victoria-metrics-stack-grafana-test
  containers:
    - name: victoria-metrics-stack-test
      image: "docker.io/bats/bats:v1.4.1"
      imagePullPolicy: "IfNotPresent"
      command: ["/opt/bats/bin/bats", "-t", "/tests/run.sh"]
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
  volumes:
    - name: tests
      configMap:
        name: victoria-metrics-stack-grafana-test
  restartPolicy: Never
