---
# Source: victoria-metrics-k8s-stack/charts/grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.59.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: victoria-metrics-stack
    app.kubernetes.io/version: "10.1.2"
    app.kubernetes.io/managed-by: Helm
  name: victoria-metrics-stack-grafana
  namespace: observability
