---
# Source: victoria-metrics-k8s-stack/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-stack-grafana
  namespace: observability
  labels:
    helm.sh/chart: grafana-6.59.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: victoria-metrics-stack
    app.kubernetes.io/version: "10.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: victoria-metrics-stack
