apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - https://broidery.k3s.com
                - https://broidery-bg.k3s.com
              max_age: 7200
    processors:

    #exporters:
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
    #  debug:
    exporters:
      logging:
        loglevel: info
      otlp:
        #endpoint: "tempo-operator-controller-manager-metrics-service.tempo-operator-system:8443"
        endpoint: "http://tempo-sample.tempo-operator-system:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp]