apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: broidery-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: broidery-backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50