apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend
- configmap
- CRDS
- ui
- upgrade
- webhook
- longhorn-critical.PriorityClass.yaml
- longhorn-driver-deployer.Deployment.yaml
- longhorn-manager.DaemonSet.yaml
- longhorn-uninstall.Job.yaml
- svc-account
