kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: [ "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  # Añade más reglas según las necesidades de monitoreo del controlador de Ingress-Nginx
