---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: grafana
type: Opaque
stringData:
  grafanadb-password: aHF1aDlGeXAxUHVMeFhmTlptbGlJaS85R0F3PQ==
  grafanadb-user: Z3JhZmFuYQ==