---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vm-victoria-metrics-k8s-stack-apiserver.VMServiceScrape.yaml
- vm-victoria-metrics-k8s-stack-coredns.VMServiceScrape.yaml
- vm-victoria-metrics-k8s-stack-metric-server.VMServiceScrape.yaml
- vm-victoria-metrics-k8s-stack-node-exporter.VMServiceScrape.yaml
- vm-victoria-metrics-k8s-stack-operator.VMServiceScrape.yaml

#EKS maneja estos componentes pro lo cual no hay pods disponibles para el scrape
#- vm-victoria-metrics-k8s-stack-kube-controller-manager.VMServiceScrape.yaml
#- vm-victoria-metrics-k8s-stack-kube-etcd.VMServiceScrape.yaml
#- vm-victoria-metrics-k8s-stack-kube-scheduler.VMServiceScrape.yaml