---
# Source: victoria-metrics-k8s-stack/templates/servicemonitors/metric-server.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vm-victoria-metrics-k8s-stack-metric-server
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: metric-server
      k8s-app: metrics-server
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: jobLabel
