apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: broidery-frontend-hpa
spec:
  scaleTargetRef:
    #apiVersion: apps/v1
    #kind: Deployment
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: broidery-frontend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50