apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-sql-schema-1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded 
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: anda-ahi-chango
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded 
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine/curl:latest
          command: ["curl", "http://broidery-frontend.default:80"]
      restartPolicy: Never