apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/autopilot-annotation: "true"
    argocd.argoproj.io/depends-on: |
      [
        {"name": "broidery-backend", "namespace": "default"}
      ]

patches:
- path: deploy.yaml
#- target:
#    group: apps
#    version: v1
#    kind: Deployment
#    name: broidery-frontend
#  path: blue-green-patch.yaml

images:
- name: spirito/broidery-fe
  newTag: fix-path #"1.6"
- name: alpine/curl
  newTag: latest

resources:
- ../../base
#- hpa.yaml
- ingress.yaml
- ingress-bg.yaml
- cm-blue.yaml
- cm-green.yaml
#- jobs.yaml

namespace: default