apiVersion: v1
data:
  grafana.ini: |
    [smtp]
    enabled = false
    from_name = grafana
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 'https://grafana.k3s'
    root_url = 'https://grafana.k3s'



kind: ConfigMap
metadata:
  labels:
    grafana_datasource: true
    app.kubernetes.io/name: grafana-central
    app.kubernetes.io/version: 10.1.5
  name: cm-grafana
  namespace: grafana
