apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: management-prd
      type: prometheus
      url: http://vmselect-vm-victoria-metrics-k8s-stack.observability:8481/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: prometheus-legacy-management
      type: prometheus
      url: https://prometheus.management.fravega.com/
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: gcp-legacy-development
      type: prometheus
      url: https://victoria-metrics.ds.development.fravega.com/
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: creditos-legacy-management
      type: prometheus
      url: https://prometheus.internal.production.creditos.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-op-kube-prometh-alertmanager.observability:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
    - name: fenix-01-dev
      type: prometheus
      url: https://victoria-metrics.fenix-01-dev.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: management-dev
      type: prometheus
      url: https://victoria-metrics.eks-fenix-01.dev.shd-ops-management.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: ecommerce-01-dev
      type: prometheus
      url: https://victoria-metrics.ecommerce-01-dev.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: fintech-01-dev
      type: prometheus
      url: https://victoria-metrics.fintech-01-dev.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: marketplace-01-dev
      type: prometheus
      url: https://victoria-metrics.marketplace-01-dev.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: shipping-01-dev
      type: prometheus
      url: https://victoria-metrics.shipping-01-dev.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: store-01-dev
      type: prometheus
      url: https://victoria-metrics.store-01-dev.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: keycloak-01-dev
      type: prometheus
      url: https://victoria-metrics.eks-keycloak-01.dev.com-iam-dev.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: fpay-01-dev
      type: prometheus
      url: https://victoria-metrics.eks-own-fpay-01.dev.own-fpay-dev.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: creditos-legacy-dev
      type: prometheus
      url: https://prometheus.internal.development.creditos.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: prometheus-legacy-dev
      type: prometheus
      url: https://prometheus.development.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: ecommerce-01-tst
      type: prometheus
      url: https://victoria-metrics.ecommerce-01-tst.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: fintech-01-tst
      type: prometheus
      url: https://victoria-metrics.fintech-01-tst.ct.fravega.com/
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: marketplace-01-tst
      type: prometheus
      url: https://victoria-metrics.marketplace-01-tst.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: shipping-01-tst
      type: prometheus
      url: https://victoria-metrics.shipping-01-tst.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: store-01-tst
      type: prometheus
      url: https://victoria-metrics.store-01-tst.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: fenix-01-tst
      type: prometheus
      url: https://victoria-metrics.fenix-01-tst.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: core-01-prd
      type: prometheus
      url: https://victoria-metrics.core-01-prd.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: ecommerce-01-prd
      type: prometheus
      url: https://victoria-metrics.ecommerce-01-prd.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: fintech-01-prd
      type: prometheus
      url: https://victoria-metrics.fintech-01-prd.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: marketplace-01-prd
      type: prometheus
      url: https://victoria-metrics.marketplace-01-prd.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: shipping-01-prd
      type: prometheus
      url: https://victoria-metrics.shipping-01-prd.ct.fravega.com/select/0/prometheus
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: store-01-prd
      type: prometheus
      url: https://victoria-metrics.store-01-prd.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: keycloak-01-prd
      type: prometheus
      url: https://victoria-metrics.eks-keycloak-01.prd.com-iam-prd.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: prometheus-legacy-prd
      type: prometheus
      url: https://prometheus.production.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: creditos-legacy-prd
      type: prometheus
      url: https://prometheus.internal.production.creditos.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: core-01-dev
      type: prometheus
      url: https://victoria-metrics.core-01-dev.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: core-01-tst
      type: prometheus
      url: https://victoria-metrics.core-01-tst.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: data-01-dev
      type: prometheus
      url: https://victoria-metrics.data-01-dev.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: data-01-tst
      type: prometheus
      url: https://victoria-metrics.data-01-tst.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: data-01-prd
      type: prometheus
      url: https://victoria-metrics.data-01-prd.ct.fravega.com
      access: proxy
      isDefault: false
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: be6lwselwmjggc
    - name: postgres-adn-vtol-adapter
      type: postgres
      access: proxy
      isDefault: false
      url: adn-production-fravega-com.c6nxv8yvgyrf.us-east-1.rds.amazonaws.com
      database: adn-vtol-adapter    
      user: app_grafana
      secureJsonData:
        password: ${POSTGRES_ADN_VTOL_ADAPTER}

kind: ConfigMap
metadata:
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 51.10.0
  name: cm-grafana-datasource
  namespace: observability
