apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: grafana-central
    app.kubernetes.io/version: 10.1.5
  name: grafana
  namespace: observability
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-web
    scheme: http
    scrapeTimeout: 30s
  jobLabel: prometheus-op
  namespaceSelector:
    matchNames:
    - observability
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana