apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-grafana
  namespace: argocd
spec:
  project: grafana
  source:
    repoURL: https://github.com/SpiritoLucas/grafana.git
    path: .  
  destination:
    server: https://kubernetes.default.svc
    namespace: logs
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=false
      - ServerSideApply=true