apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-grafana
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://github.com/SpiritoLucas/grafana.git
    path: .  
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true