apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-grafana.yaml
- cm-grafana-config-dashboards.yaml
- cm-grafana-datasource.yaml
- cm-grafana-overview.yaml
- cm-grafana.yaml
- crb-grafana.yaml
- deploy-grafana.yaml
- grafana-ingress.yaml
- grafana-pvc.yaml
- rb-grafana.yaml
- role-grafana.yaml
- sa-grafana.yaml
#- svc-monitor.yaml
- svc.yaml
- ../../base