apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: grafana-central
    app.kubernetes.io/version: 10.1.5
  name: role-grafana
  namespace: grafana
rules: null
