apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana-vpa
  namespace: grafana
  labels:
    creator: "Fairwinds"
    source: "goldilocks"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: grafana
  updatePolicy:
    updateMode: "Recreate"
