apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/autopilot-annotation: "true"
    argocd.argoproj.io/depends-on: |
      [
        {"name": "broidery-frontend", "namespace": "default"}
      ]

images:
- name: alpine/curl
  newTag: latest

resources:
- jobs.yaml

namespace: default