---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vm-cluster-autoscaler-VMRule.yaml
- vm-victoria-metrics-k8s-stack-alertmanager.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-etcd.VMRule.yaml
- vm-victoria-metrics-k8s-stack-general.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-k8s.rules.containercpuusagesecond.VMRule.yaml
- vm-victoria-metrics-k8s-stack-k8s.rules.containermemorycache.VMRule.yaml
- vm-victoria-metrics-k8s-stack-k8s.rules.containermemoryrss.VMRule.yaml
- vm-victoria-metrics-k8s-stack-k8s.rules.containermemoryswap.VMRule.yaml
- vm-victoria-metrics-k8s-stack-k8s.rules.containermemoryworkings.VMRule.yaml
- vm-victoria-metrics-k8s-stack-k8s.rules.containerresource.VMRule.yaml
- vm-victoria-metrics-k8s-stack-k8s.rules.podowner.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-apiserver-availability.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-apiserver-burnrate.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-apiserver-histogram.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-apiserver-slos.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-prometheus-general.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-prometheus-node-recording.ru.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-scheduler.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kube-state-metrics.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kubelet.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kubernetes-apps.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kubernetes-resources.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kubernetes-storage.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kubernetes-system-apiserver.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kubernetes-system-kubelet.VMRule.yaml
- vm-victoria-metrics-k8s-stack-kubernetes-system.VMRule.yaml
- vm-victoria-metrics-k8s-stack-node-exporter.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-node-exporter.VMRule.yaml
- vm-victoria-metrics-k8s-stack-node-network.VMRule.yaml
- vm-victoria-metrics-k8s-stack-node.rules.VMRule.yaml
- vm-victoria-metrics-k8s-stack-vm-health.VMRule.yaml
- vm-victoria-metrics-k8s-stack-vmagent.VMRule.yaml
