---
# Source: victoria-metrics-k8s-stack/templates/rules/kube-prometheus-general.rules.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: observability
  name: vm-victoria-metrics-k8s-stack-kube-prometheus-general.rules
  labels:
    app: victoria-metrics-k8s-stack
    helm.sh/chart: victoria-metrics-k8s-stack-0.19.2
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: vm
    app.kubernetes.io/version: "v1.98.0"
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
    - name: kube-prometheus-general.rules
      rules:
        - expr: count without(instance, pod, node) (up == 1)
          record: count:up1
        - expr: count without(instance, pod, node) (up == 0)
          record: count:up0
