---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vm-victoria-metrics-k8s-stack-operator.ConfigMap.yaml
- vm-victoria-metrics-operator-cleanup-hook.ClusterRole.yaml
- vm-victoria-metrics-operator-cleanup-hook.ClusterRoleBinding.yaml
- vm-victoria-metrics-operator-cleanup-hook.Job.yaml
- vm-victoria-metrics-operator-cleanup-hook.ServiceAccount.yaml
- vm-victoria-metrics-operator.ClusterRole.yaml
- vm-victoria-metrics-operator.ClusterRoleBinding.yaml
- vm-victoria-metrics-operator.Deployment.yaml
- vm-victoria-metrics-operator.Role.yaml
- vm-victoria-metrics-operator.RoleBinding.yaml
- vm-victoria-metrics-operator.Service.yaml
- vm-victoria-metrics-operator.ServiceAccount.yaml
