---
# Source: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/uninstall_hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-victoria-metrics-operator-cleanup-hook
  namespace: observability
  labels:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: vm
    helm.sh/chart: victoria-metrics-operator-0.28.1
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vm-victoria-metrics-operator-cleanup-hook
subjects:
  - kind: ServiceAccount
    name: vm-victoria-metrics-operator-cleanup-hook
    namespace: observability
