---
# Source: immich/templates/server.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: server
    app.kubernetes.io/version: v1.119.0
    helm.sh/chart: immich-0.9.3
spec:
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: immich
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:v1.119.0
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_DATABASE_NAME
          value: immich
        - name: DB_HOSTNAME
          value: postgres.immich.svc.cluster.local
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
        - name: DB_USERNAME
          value: immich
        - name: IMMICH_MACHINE_LEARNING_URL
          value: http://immich-machine-learning.immich.svc.cluster.local:3003
        - name: REDIS_HOSTNAME
          value: redis.immich.svc.cluster.local
        ports:
        - name: http
          containerPort: 2283
          protocol: TCP
        volumeMounts:
        - name: library
          mountPath: /usr/src/app/upload
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/server/ping
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/server/ping
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /api/server/ping
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 300m
            memory: 2Gi
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: immich-library-pvc
