---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- victoria-metrics-stack-victoria-metrics-k8s-stack-coredns.Service.yaml
- victoria-metrics-stack-victoria-metrics-k8s-stack-coredns.VMServiceScrape.yaml
