apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kubernetes-pods
  namespace: observability
  labels:
    name: kubernetes-pods
spec:
  podMetricsEndpoints:
    - scheme: http
      relabelConfigs:
        - sourceLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - sourceLabels:
            [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels:
            [
                __address__,
                __meta_kubernetes_pod_annotation_prometheus_io_port,
            ]
          action: replace
          targetLabel: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
        - separator: ;
          regex: __meta_kubernetes_pod_label_(.+)
          replacement: $1
          action: labelmap
        - sourceLabels:
            [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace
          regex: (.*)
        - sourceLabels:
            [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
          regex: (.*)
  namespaceSelector:
    any: true
