apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack
  namespace: argocd
spec:
  project: observability
  source:
    helm:
      values: |
        vmsingle:
          enabled: true
          spec:
            retentionPeriod: "7"
            storage:
              resources:
                requests:
                  storage: 50Gi
        crds:
          enabled: true
        prometheus-node-exporter:
          enabled: false
        grafana:
          enabled: true
          sidecar:
          ingress:
            ingressClassName: nginx
            hosts:
              - grafana.k3s
            tls:
              - secretName: cluster-dns
                hosts:
                  - grafana.k3s
  destination:
    namespace: victoria-metrics
