---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: observability 
  source:
    helm:
      values: |
        traces:
          otlp:
            http:
              # -- Enable Tempo to ingest Open Telemetry HTTP traces
              enabled: true
            grpc:
              # -- Enable Tempo to ingest Open Telemetry GRPC traces
              enabled: true