apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-rollouts-autodiscovery.yaml
- argocd-autodiscovery.yaml
- broidery-autodiscovery.yaml
- certs-autodiscovery.yaml
- discord-bot-autodiscovery.yaml
- goldilocks-autodiscovery.yaml
- grafana-autodiscovery.yaml
- immich-autodiscovery.yaml
- kube-system-autodiscovery.yaml
- kubernetes-dashboard-autodiscovery.yaml
- letsencript-autodiscovery.yaml
- metallb-autodiscovery.yaml
- metric-server-autodiscovery.yaml
- nginx-autodiscovery.yaml
- observability-autodiscovery.yaml
- opentelemetry-operator-autodiscovery.yaml
- stremio-autodiscovery.yaml
- vault-autodiscovery.yaml
- victoriametrics-autodiscovery.yaml

