---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vm-victoria-metrics-k8s-stack-backupmanager.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-grafana-overview.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-k8s-views-global.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-k8s-views-namespaces.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-k8s-views-pods.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-vmagent.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-vmalert.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-alertmanager-overview.ConfigMap.yaml
