apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-role-bindings.yaml
- cluster-roles.yaml
- crds.yaml
- daemonset.yaml
- deploy.yaml
- ns.yaml
- rolebindings.yaml
- roles.yaml
- secret.yaml
- svc-accounts.yaml
- svc.yaml
- validatingwhconfig.yaml
- cm.yaml