---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: immich
spec:
  serviceName: "redis"
  PriorityClassName: app-high-priority
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
          args: ["--appendonly", "yes"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 2Gi
