apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: sf.yaml
- path: cm.yaml

images:
- name: mysql
  newTag: "5.7"

resources:
- ../../base
- sealed-secret.yaml

namespace: default