apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_PASSWORD: AgB51yL5b1jCIGdivnD7CUVBKGI5/cNN0P3EwHGlxMFPKO0GP0+N2/nO8NQyGve6bFnLHG0xRWCUgxHC1Hg8DSVxcDxKU7ZCBSaVZxpdkN/b5jApxMQEdcAp8gdoZ/03wguCEdJD9OBbCYQTp4r8GJ55r0n1Balh8x17UxI+VO2W0udiGt7nP3oBWfuuLY90KMSbZHkMTWJxcjIORGmnIhdkrw1Fy8nyf0FMizfhhCl8idPDukH6/VPV7Heb2Ck8ixlMYmF9S/ipOlCLIF8d47O/I77Y2u1OGsk+Z6Qf/glzXO2RV+9jaT1XhS0EvLwDSSjrfts11eQGkD5XRMrCNIGXqgVWCXtgHpIR2N4PBLYD4MqFQADPVrvloHiEOjFCvy1kTeFe2rWKBijd5VGV4BJizglnJ9DVKLBAT6IbAb++2lCZxaOgjqvZXObz9fp89m02bPwthcJ78xIuU0/HY7McoEji0slb5E6jtnkg0EBnVBUtutoqc2tKVnenihXTkx85a1y1J9ys25L1MH5HYvdXoUkuKSJ9r1QKv1n9iNSiPAdZqArUUjtMluy1moN1SLqFhb5rhC3gnbhtFw+wXh/CcrJQvgZUh1X/ez8kOrRV+UfOgsVT6mVZAlstb9mba9lfyDmS2uSfSu6a7kxuTUh3fIG9SW6LJEBci5iEpepmYt+giK3IZ8260wraVVEFYCwbMXZYrfN156A61ffPJc5w
    MYSQL_ROOT_PASSWORD: AgA/Pf14ARzK86ZG8rkDkC0jh1iBE4FWFxRHNtW5j76ag/Mh0G4+6u2UzE0NlxUZ26CBcuBEtYsR5mtNjaccKJ/hn7r+73IEk3onRFf+kdulTOQWef1dxlR6l/WikYY/GYBNEl1n6BnrX3A24e2aU08jDEFUr/6uoFyuMcUyQ2ssNGO2j4w57wSQ06W1o4HBwAbPI/nUy8hJ7nAOXTmeD/84ZwOYzBb2ApphQCLPXwNcpqaCutZXGfHbfgNTrPk3TGNyoLLiKXBNLZxrjI+S73X0PFAWHM/HH2HMegR+AqHIDNkBwsquQujwdmco3s/Sde8pwLhifhfCRDFpJmmhehzcZdHt4NLkGTgWQobUL2z4zrfpiD3DLl2XveScDtSSSvILzLEaATwzQHxqVwnXKK5oZFGWr2bGobthQsDpjdlqO3K40c31OIYJTgtwwhKaX31Z6q2U9SzjhmpbnPT4jBHaNldCdL9wDBcz95kNRhVgXhLt3atf0rzctqVDbxw+7E2PB8Si+ppix4WACzVDtBh2hk4M7HxlR6UH0GjBCmwqX0sZErn+BLVgqbs3wxWKzcYRuzOpIQSV8vd0nrCojDSdp/5zfd/OmuUuhbAepCna9cNL2xIMmnOvUBzOmrXSM0YnCtO6cRgV7XwRDLTlphbrxhcU/7ylpSAXUoQlN0R9xWRQH+jYDc0RdhV5X9iGkGDCRKAVfN2zTVe6zpSjq1fD
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque

