---
# Source: victoria-metrics-k8s-stack/templates/rules/vmagent.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: observability
  name: vm-victoria-metrics-k8s-stack-vmagent
  labels:
    app: victoria-metrics-k8s-stack
    helm.sh/chart: victoria-metrics-k8s-stack-0.18.11
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: victoria-metrics-stack
    app.kubernetes.io/version: "v1.96.0"
    app.kubernetes.io/managed-by: Helm
spec:
  groups:
    - concurrency: 2
      interval: 30s
      name: vmagent
      rules:
        - alert: PersistentQueueIsDroppingData
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=49&var-instance={{ $labels.instance }}
            description: Vmagent dropped {{ $value | humanize1024 }} from persistent queue on instance {{ $labels.instance }} for the last 10m.
            summary: Instance {{ $labels.instance }} is dropping data from persistent queue
          expr: sum(increase(vm_persistentqueue_bytes_dropped_total[5m])) by (job, instance) > 0
          for: 10m
          labels:
            severity: critical
        - alert: RejectedRemoteWriteDataBlocksAreDropped
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=79&var-instance={{ $labels.instance }}
            summary: Job "{{ $labels.job }}" on instance {{ $labels.instance }} drops the rejected by remote-write server data blocks. Check the logs to find the reason for rejects.
          expr: sum(increase(vmagent_remotewrite_packets_dropped_total[5m])) by (job, instance) > 0
          for: 15m
          labels:
            severity: warning
        - alert: TooManyScrapeErrors
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=31&var-instance={{ $labels.instance }}
            summary: Job "{{ $labels.job }}" on instance {{ $labels.instance }} fails to scrape targets for last 15m
          expr: sum(increase(vm_promscrape_scrapes_failed_total[5m])) by (job, instance) > 0
          for: 15m
          labels:
            severity: warning
        - alert: TooManyWriteErrors
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=77&var-instance={{ $labels.instance }}
            summary: Job "{{ $labels.job }}" on instance {{ $labels.instance }} responds with errors to write requests for last 15m.
          expr: |-
            (sum(increase(vm_ingestserver_request_errors_total[5m])) by (job, instance)
            +
            sum(increase(vmagent_http_request_errors_total[5m])) by (job, instance)) > 0
          for: 15m
          labels:
            severity: warning
        - alert: TooManyRemoteWriteErrors
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=61&var-instance={{ $labels.instance }}
            description: "Vmagent fails to push data via remote write protocol to destination \"{{ $labels.url }}\"\n Ensure that destination is up and reachable."
            summary: Job "{{ $labels.job }}" on instance {{ $labels.instance }} fails to push to remote storage
          expr: sum(rate(vmagent_remotewrite_retries_count_total[5m])) by(job, instance, url) > 0
          for: 15m
          labels:
            severity: warning
        - alert: RemoteWriteConnectionIsSaturated
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=84&var-instance={{ $labels.instance }}
            description: "The remote write connection between vmagent \"{{ $labels.job }}\" (instance {{ $labels.instance }}) and destination \"{{ $labels.url }}\" is saturated by more than 90% and vmagent won't be able to keep up.\n This usually means that `-remoteWrite.queues` command-line flag must be increased in order to increase the number of connections per each remote storage."
            summary: Remote write connection from "{{ $labels.job }}" (instance {{ $labels.instance }}) to {{ $labels.url }} is saturated
          expr: "(\n sum(rate(vmagent_remotewrite_send_duration_seconds_total[5m])) by(job, instance, url) \n / \n max(vmagent_remotewrite_queues) by(job, instance, url)\n) > 0.9"
          for: 15m
          labels:
            severity: warning
        - alert: PersistentQueueForWritesIsSaturated
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=98&var-instance={{ $labels.instance }}
            description: Persistent queue writes for vmagent "{{ $labels.job }}" (instance {{ $labels.instance }}) are saturated by more than 90% and vmagent won't be able to keep up with flushing data on disk. In this case, consider to decrease load on the vmagent or improve the disk throughput.
            summary: Persistent queue writes for instance {{ $labels.instance }} are saturated
          expr: rate(vm_persistentqueue_write_duration_seconds_total[5m]) > 0.9
          for: 15m
          labels:
            severity: warning
        - alert: PersistentQueueForReadsIsSaturated
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=99&var-instance={{ $labels.instance }}
            description: Persistent queue reads for vmagent "{{ $labels.job }}" (instance {{ $labels.instance }}) are saturated by more than 90% and vmagent won't be able to keep up with reading data from the disk. In this case, consider to decrease load on the vmagent or improve the disk throughput.
            summary: Persistent queue reads for instance {{ $labels.instance }} are saturated
          expr: rate(vm_persistentqueue_read_duration_seconds_total[5m]) > 0.9
          for: 15m
          labels:
            severity: warning
        - alert: SeriesLimitHourReached
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=88&var-instance={{ $labels.instance }}
            description: Max series limit set via -remoteWrite.maxHourlySeries flag is close to reaching the max value. Then samples for new time series will be dropped instead of sending them to remote storage systems.
            summary: Instance {{ $labels.instance }} reached 90% of the limit
          expr: (vmagent_hourly_series_limit_current_series / vmagent_hourly_series_limit_max_series) > 0.9
          labels:
            severity: critical
        - alert: SeriesLimitDayReached
          annotations:
            dashboard: grafana.domain.com/d/G7Z9GzMGz?viewPanel=90&var-instance={{ $labels.instance }}
            description: Max series limit set via -remoteWrite.maxDailySeries flag is close to reaching the max value. Then samples for new time series will be dropped instead of sending them to remote storage systems.
            summary: Instance {{ $labels.instance }} reached 90% of the limit
          expr: (vmagent_daily_series_limit_current_series / vmagent_daily_series_limit_max_series) > 0.9
          labels:
            severity: critical
        - alert: ConfigurationReloadFailure
          annotations:
            description: Configuration hot-reload failed for vmagent on instance {{ $labels.instance }}. Check vmagent's logs for detailed error message.
            summary: Configuration reload failed for vmagent instance {{ $labels.instance }}
          expr: |-
            vm_promscrape_config_last_reload_successful != 1
            or
            vmagent_relabel_config_last_reload_successful != 1
          labels:
            severity: warning
