---
# Source: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: victoria-metrics-stack-victoria-metrics-operator
  namespace: observability
  labels:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: victoria-metrics-stack
    helm.sh/chart: victoria-metrics-operator-0.27.4
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: victoria-metrics-stack-victoria-metrics-operator
    namespace: observability
roleRef:
  kind: Role
  name: victoria-metrics-stack-victoria-metrics-operator
  apiGroup: rbac.authorization.k8s.io
