---
# Source: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/uninstall_hook.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoria-metrics-stack-victoria-metrics-operator-cleanup-hook
  namespace: observability
  labels:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: victoria-metrics-stack
    helm.sh/chart: victoria-metrics-operator-0.27.4
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
