---
# Source: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  labels:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: victoria-metrics-stack
    helm.sh/chart: victoria-metrics-operator-0.27.4
    app.kubernetes.io/managed-by: Helm
  name: victoria-metrics-stack-victoria-metrics-operator
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: webhook
      port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: victoria-metrics-operator
    app.kubernetes.io/instance: victoria-metrics-stack
  type: "ClusterIP"
