apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: certificates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    notifications.argoproj.io/subscribe.discord_k3s_success: ""
    notifications.argoproj.io/subscribe.discord_k3s_error: ""
spec:
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      namespaces:
        - certificates
      clusters:
        - in-cluster
  description: k3s Team
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'https://github.com/SpiritoLucas/**'
  # Allow managing monitoring namespace
  destinations:
    - namespace: certificates
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'