---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vmagents.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmalertmanagerconfigs.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmalertmanagers.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmalerts.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmauths.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmclusters.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmnodescrapes.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmpodscrapes.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmprobes.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmrules.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmservicescrapes.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmsingles.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmstaticscrapes.operator.victoriametrics.com.CustomResourceDefinition.yaml
- vmusers.operator.victoriametrics.com.CustomResourceDefinition.yaml
