---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - vmagent-vm-victoria-metrics-k8s-stack.Ingress.yaml
  - vmalertmanager-vm-victoria-metrics-k8s-stack.Ingress.yaml
  - vmsingle-vm-victoria-metrics-k8s-stack.Ingress.yaml
