---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - ../../../../../Bases/victoria-metrics/v2/vmsingle

patches:
  - path: vm-victoria-metrics-k8s-stack.VMAgent.yaml
  - path: vm-victoria-metrics-k8s-stack.VMAlertmanager.yaml
  - path: vmagent-vm-victoria-metrics-k8s-stack.Ingress.yaml
  - path: vmalertmanager-vm-victoria-metrics-k8s-stack.Ingress.yaml
  - path: vmsingle-vm-victoria-metrics-k8s-stack.Ingress.yaml
