---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vm-kube-state-metrics.ClusterRole.yaml
- vm-kube-state-metrics.ClusterRoleBinding.yaml
- vm-kube-state-metrics.Deployment.yaml
- vm-kube-state-metrics.Service.yaml
- vm-kube-state-metrics.ServiceAccount.yaml
- vm-victoria-metrics-k8s-stack-kube-state-metrics.VMServiceScrape.yaml
