apiVersion: batch/v1
kind: Job
metadata:
  name: checker
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded 
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
        - name: check-1
          image: 
          command: ["-n", "10000", "-c", "10", "-H", "Host: broidery-backend.k3s", "https://192.168.64.26/health-check"]
      restartPolicy: Never