apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: spirito/broidery-be
  newTag: 1.1.1
  #newTag: otel-logs

resources:
- ../../base
- sealed-secret.yaml
#- job.yaml
#- hpa.yaml
- analysisTemplate.yaml

namespace: default

patches:
- path: deploy.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: broidery-backend
  path: canary-patch.yaml

#transformers:
#- custom-labels.yaml
