apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-connection
  namespace: default
spec:
  encryptedData:
    DEFAULT_CONNECTION: AgAOcUWsdmA+CRS2xbGV9OuLvDgMGifivM/mGALpybfrm/9tcZSQ3Fv0rNnnVAv2C0YAnPqie91bzRM8VrouZ6vW0fjV8y0Xuvrr7geXBQ5PTmQrIXVwNxFxX4Stzh6Eo5x+Io+bLcDXK6rkkoPiOEG0MP7dOhEojnosd0BzPGhysHP6RnQ39dkxRDAMBIxTv8et9089HwrWaefz525X2BhG1KDbV/hjXA/amdjwIeLBpSqIfbNwsJTBvASXQMJBDBT7oK7lkRXSmTrCllU0Sftp4DyCu2ZjfFDgUaE3mj17PwmmnuWocY+SIkf3md9OiceyAxlxzA9XXbDiD0r8FLzUsCa6PWJm13lfrYATPqeYUO7l+iHJ9Rw/Zo+MZOmMXIEoF2PDDw6qLCb0ovTjtrRjoWuc2HzaYQRMTgaRCIKeWZj501+MuAtsLHKXNi0khdt9H7jIZv/1hFDHkLesUjPiB7FWm1CJj/ggUNp3Vma+XjF8omTqdcfw7p9uB7D8yG/RgIOEXAhszebjpdSG3oGilTggpTdJ0hcq4kyxBffsKqJqqqxtvTyfsZWdzHvV2qeqS9rY464QC6qxstJ3MXblEpEnCOUfaS+iifcZA2ssi3n8ZEeDivSUbU9wjjSxHPumLI1m4W3PKdOp6lo2fKgjEfPsCxQch1T+tmLByxdDRG+YG56w799Vo3Ae23MiqMZbWxKKXYtxmcn9GSbKI8v311yiE2CSjQb4ip0LzcFAgRH7e/FLOciO/WC28EoufKisYnrrJgT5FoMoC87misuNnbn8KBoL5LDt7vUOtDUbd6xpckkGBePhnjQ9ZLN/SBQRQ9TaG4HVGekU1zP7H8SxrPfCmlxRMMJCdQ==
  template:
    metadata:
      creationTimestamp: null
      name: default-connection
      namespace: default
    type: Opaque

