apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-connection
  namespace: default
spec:
  encryptedData:
    DEFAULT_CONNECTION: AgBlahlU8elZgT5o0oKGMkqs1dqa6HMKZ0sDHM26Tb2sT4LjRA10Hqd0Cc9io8GkYm83yMHEpBLsn5SduPjR4XCIYWuNZZSCYtz0+MFLpZlieurxvIcu6sljR6DD2vw3Fl+8dAYyz6bUl45egaOD8J77QhYB/5Ei+YPAIDXje5N7CTEacxFUEA2JdUq8mx6aO7LPkCVo395NnE1koKQSKdvgJDIr3193pk8vmLgGazuzh7PhEkVA4nbQrttyoWUy8qcCa2Hq12ptM+f8IjSuFCs79PTxuT6p1ECjsJ4EuX74OP4tLs+HoNB9Jkzj/yRpUEh8qKa/t/+woqKQyIu2cJNgVywZstVhOIiS8RsZrcVSrmYBp7KLjnRkcxy8Cm+KMobM/YHwmZuMxkyFatYfXO+5z1XAbcnvnghGLxkAvEeNSoKEjLCcn2QGO4ON/xwppE9URVIhdCtNagdp6sUyY5TI/KfkRwwSF3grXf7gPB9Voso+14x+msi/2aaa4SDyHDWAh0ufprP+E2Pgx2fvPNX5nPUUolmadKHJA7kKg+D699xPW146SB5pqK2lUCsNj9IvGtZyee9dCvYTCuqZDi9dOdw5GA1dWjVSIMak5lJDquzH9Oh4LbI41yeQU6FaStr/SIAQ19+iCr0MhkuIZhvj1DTibwjWlAH3vf0baJx6gvKxrRyBUuGztdOF4wmQDzX1IzwjbPvRdn+h/VKEwRKbDh4na7lmciOS08E1MZxrGhJI5UqfEH2ENF6wZI8uurrizm/SNICa8wQUhrbFSVFyRUnPY0ajvFVcaRYUDjz5lxjDZqoH7hVNuvJz0kiy57WPTMEudQzcb3HV+JJxZZ5UpOxTfVVRRoRMfQ==
  template:
    metadata:
      creationTimestamp: null
      name: default-connection
      namespace: default
    type: Opaque

