apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: default-connection
  namespace: default
spec:
  encryptedData:
    DEFAULT_CONNECTION: AgBMEsgIYQy5Np9vYoCzvkkUvg0kCLYj70irMocX6KKs84JVobsSSrmDLj1igBYw9MXroKDCaxektrKrCVrsVm6F5G82xDHFca5zj8AoxsFhTnHQvhprlb2XwUYXg4wS+ITx65og3iM59RoFPZOfHiEhtNmjgi3LCQVqtg5s3yx00dHE8hGbzPDiAcVLoVYHJBreVbRbZkEieey8plHy76TF7en1e0SxQOmYuyiR7GBDBNuVfll4pPJmsgwPESIMDpOnk7WLPMny8x0PF2kXE+opaz7LrEKssyOJPThLQA/VK5IA+1FuKXR5ZT0ceiN3u/J1/0iPsfYdrFuqwSEjLTIsL7SErLMtzPRSDC5a/s04uCakTWHDUItQRbPGRHczXUxrGNNl82pa+appv5eh3KCWNoVTotfb1mBdqu02y/9MQc+rfQrsXZfjO1ASKFs1CcO1OO35ay37MmhHlZInfLc0LwDFnZpkJ8j2Bvly7RJi16blCSLv18MvJT2Q1v+mrAt1Ora7WKAMZPaUoAiEk+VG/QOZZk7mPL1yLCj2l8POvOwNk2c1vJqFWTiHYrWGp7kZ1Ako9G+OoGjaiyExittFxiXd1t2v8OYHwWyfL+Md/q86W94xLZkA5YGGGhi0AkSQX1gdR5FMU45bssJfTj9l0I9l70AWaurRvPm5dvaQ0q/IM5Dw3ZmQzlyS0jwu0EIa3hYpx/AXqfn9FmogL/F6E4wAfjBnUAsfqZvrReVJMFQmAjv3pL2RmW3OzScKLRpIBCUth8u2p60gu2GZqEHQ/SdNnVuw4D+T7Y8w8wB3Fb7ibaem6OvNaWCzgiSBTjhZxYjgVfDuH9VnMY5xeSFb6X7gIE1ktI5JxA==
  template:
    metadata:
      creationTimestamp: null
      name: default-connection
      namespace: default
    type: Opaque

