apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: exporter-binding
subjects:
- kind: ServiceAccount
  name: exporter
  namespace: observability
roleRef:
  kind: ClusterRole
  name: exporter-cluster-role
  apiGroup: rbac.authorization.k8s.io