apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-cm
data:
  ENVIRONMENT: development
  METRICS_EXPORTER_TEMPORALITY_PREFERENCE: cumulative
  METRICS_EXPORTER_CUMULATIVE_TEMPORALITY_ENDPOINT: opentelemetry-collector.observability:4318
  OTEL_TRACES_EXPORTER: none
  OTEL_METRICS_EXPORTER: none
  OTEL_LOGS_EXPORTER: none
  SERVER_PORT: '8000'
  SEMANTIC_REGEX: r'^([0-9]+\.){1,2}[0-9]+$'
  LAST_CONFIG_REGEX: r'^.1.1.1.*'
  PROMQL_QUERY: 'avg by (image, namespace, pod) (kube_pod_container_info{image=~".*:[0-9]+(.[0-9]+){1,2}""})'
  VICKY_METRICS_INTERNAL_URL: http://vmsingle-vm-victoria-metrics-k8s-stack.victoria-metrics:8429/prometheus