apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: spirito/last-applied-config-exporter
  newTag: latest

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- cm.yaml
- deployment.yaml
- serviceaccount.yaml
