---
# Source: victoria-metrics-k8s-stack/templates/servicemonitors/kube-etcd.yaml
apiVersion: v1
kind: Service
metadata:
  name: vm-victoria-metrics-k8s-stack-kube-etcd
  namespace: kube-system
  labels:
    app: vm-victoria-metrics-k8s-stack-kube-etcd
    jobLabel: kube-etcd
    helm.sh/chart: victoria-metrics-k8s-stack-0.18.11
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: victoria-metrics-stack
    app.kubernetes.io/version: "v1.96.0"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    component: etcd
  type: ClusterIP
