---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager
#- ConfigMap
- coredns
- CRDS
- kube-state-metrics
- operator
- prometheus-node-exporter
- VMNodeScrape
- VMRule
- VMServiceScrape
- vm-victoria-metrics-k8s-stack-kube-controller-manager.Service.yaml
- vm-victoria-metrics-k8s-stack-kube-etcd.Service.yaml
- vm-victoria-metrics-k8s-stack-kube-scheduler.Service.yaml
- vm-victoria-metrics-k8s-stack.ServiceAccount.yaml
- vm-victoria-metrics-k8s-stack.VMAlertmanager.yaml
- pods-scrape.yaml
- vmagent-vm-victoria-metrics-k8s-stack.Ingress.yaml