---
# Source: immich/templates/machine-learning.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: machine-learning
    app.kubernetes.io/version: v1.119.0
    helm.sh/chart: immich-0.9.3
spec:
  revisionHistoryLimit: 3
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: machine-learning
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: machine-learning
        app.kubernetes.io/instance: immich
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:v1.119.0
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_DATABASE_NAME
          value: immich
        - name: DB_HOSTNAME
          value: immich-postgresql.imich.svc.cluster.local
        - name: DB_PASSWORD
          value: immich
        - name: DB_USERNAME
          value: immich
        - name: IMMICH_MACHINE_LEARNING_URL
          value: http://immich-machine-learning.imich.svc.cluster.local:3003
        - name: REDIS_HOSTNAME
          value: redis.immich.svc.cluster.local
        - name: TRANSFORMERS_CACHE
          value: /cache
        ports:
        - name: http
          containerPort: 3003
          protocol: TCP
        volumeMounts:
        - name: cache
          mountPath: /cache
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: cache
        emptyDir: {}
