---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vm-unified-query-victoria-metrics.Service.yaml
- vm-victoria-metrics-k8s-stack-victoriametrics.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack.VMAgent.yaml
- vm-victoria-metrics-k8s-stack.VMAlert.yaml
- vm-victoria-metrics-k8s-stack.VMSingle.yaml
- vm-victoria-metrics-k8s-stack-vmsingle.VMRule.yaml
- vmsingle-vm-victoria-metrics-k8s-stack.Ingress.yaml
- ../common