apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack 
  namespace: argocd
spec:
  project: victoria-metrics
  source:
    repoURL: https://github.com/VictoriaMetrics/helm-charts.git
    path: charts/victoria-metrics-k8s-stack
    targetRevision: victoria-metrics-k8s-stack-0.19.2 #master
    helm:
      releaseName: vm
      valueFiles:
        - values.yaml
      #TODO validar linea 18
      values: |
        argocdReleaseOverride: victoria-metrics-stack 
        grafana:
          enabled: false
        vmagent:
          enabled: true 
          spec:
            extraArgs:
              promscrape.dropOriginalLabels: "false"
        vmsingle:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: 'false'
              nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
              cert-manager.io/issuer: "cluster-issuer-selfsigned" 
              cert-manager.io/issuer-kind: "ClusterIssuer"
              metallb.uniberse.tf/address-pool: default
            labels: 
              app.kubernetes.io/component: monitoring
              app.kubernetes.io/instance: vm-victoria-metrics-k8s-stack
              app.kubernetes.io/managed-by: Helm
              app.kubernetes.io/name: vmsingle
              app.kubernetes.io/version: v1.96.0
              helm.sh/chart: victoria-metrics-k8s-stack-0.18.11
              managed-by: vm-operator
            pathType: Prefix

            hosts:
              - victoria-metrics.k3s
            tls: 
              - secretName: victoria-metrics.k3s.cloud-tls
                hosts:
                  - victoria-metrics.k3s

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true