apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack 
  namespace: argocd
spec:
  project: victoria-metrics
  source:
    repoURL: https://github.com/VictoriaMetrics/helm-charts.git
    path: charts/victoria-metrics-k8s-stack
    targetRevision: victoria-metrics-k8s-stack-0.19.2 #master
    helm:
      releaseName: vm
      valueFiles:
        - values.yaml
      values: |
        grafana:
          enabled: false
        vmagent:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true