apiVersion: v1
kind: Service
metadata:
  name: unified-query-victoria-metrics
  namespace: observability
spec:
  ports:
    - name: http
      port: 8429
      protocol: TCP
      targetPort: 8429
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: vm-victoria-metrics-k8s-stack
    app.kubernetes.io/name: vmsingle
  sessionAffinity: None
  type: ClusterIP