---
# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/vmagent/vmagent.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm-victoria-metrics-k8s-stack
  namespace: observability
  labels:
    helm.sh/chart: victoria-metrics-k8s-stack-0.19.2
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: vm
    app.kubernetes.io/version: "v1.98.0"
    app.kubernetes.io/managed-by: Helm
spec:
  externalLabels:
    cluster: shd-ops-management
  extraArgs:
    promscrape.dropOriginalLabels: "true"
    promscrape.maxScrapeSize: 320MB
  image:
    pullPolicy: IfNotPresent
    repository: registry.gitlab.com/fravega-it/arquitectura/docker-images-vault
    tag: vmagent_v1.98.0
  imagePullSecrets:
    - name: gitlab-fvg-regcreds
  remoteWrite:
    - url: http://vmsingle-vm-victoria-metrics-k8s-stack.observability.svc:8429/api/v1/write
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: "1"
      memory: 2Gi
  scrapeInterval: 20s
  selectAllByDefault: true
