apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backingimagedatasources.longhorn.io.CustomResourceDefinition.yaml
- backingimagemanagers.longhorn.io.CustomResourceDefinition.yaml
- backingimages.longhorn.io.CustomResourceDefinition.yaml
- backupbackingimages.longhorn.io.CustomResourceDefinition.yaml
- backups.longhorn.io.CustomResourceDefinition.yaml
- backuptargets.longhorn.io.CustomResourceDefinition.yaml
- backupvolumes.longhorn.io.CustomResourceDefinition.yaml
- engineimages.longhorn.io.CustomResourceDefinition.yaml
- engines.longhorn.io.CustomResourceDefinition.yaml
- instancemanagers.longhorn.io.CustomResourceDefinition.yaml
- nodes.longhorn.io.CustomResourceDefinition.yaml
- orphans.longhorn.io.CustomResourceDefinition.yaml
- recurringjobs.longhorn.io.CustomResourceDefinition.yaml
- replicas.longhorn.io.CustomResourceDefinition.yaml
- settings.longhorn.io.CustomResourceDefinition.yaml
- sharemanagers.longhorn.io.CustomResourceDefinition.yaml
- snapshots.longhorn.io.CustomResourceDefinition.yaml
- supportbundles.longhorn.io.CustomResourceDefinition.yaml
- systembackups.longhorn.io.CustomResourceDefinition.yaml
- systemrestores.longhorn.io.CustomResourceDefinition.yaml
- volumeattachments.longhorn.io.CustomResourceDefinition.yaml
- volumes.longhorn.io.CustomResourceDefinition.yaml
