apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: spirito/broidery-be
  newTag: "1.5" #"1.4"

resources:
- ../../base
- sealed-secret.yaml

namespace: default

patches:
- path: deploy.yaml
