---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vm-victoria-metrics-k8s-stack-alertmanager-monzo-tpl.ConfigMap.yaml
- vm-victoria-metrics-k8s-stack-alertmanager.Secret.yaml
- vmalertmanager-vm-victoria-metrics-k8s-stack.Ingress.yaml
