---
# Source: victoria-metrics-k8s-stack/templates/victoria-metrics-operator/alertmanager/vmalertmanager.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vm-victoria-metrics-k8s-stack-alertmanager
  namespace: observability
  labels:
    app.kubernetes.io/component: victoria-metrics-k8s-stack-alertmanager
    helm.sh/chart: victoria-metrics-k8s-stack-0.19.2
    app.kubernetes.io/name: victoria-metrics-k8s-stack
    app.kubernetes.io/instance: vm
    app.kubernetes.io/version: "v1.98.0"
    app.kubernetes.io/managed-by: Helm
stringData:
  alertmanager.yaml: |-
    global:
      smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
      smtp_from:    'grafana@monitoring.fravega.com'
      smtp_auth_username: AKIAWTMUQEADELVHBQWO
      smtp_auth_password: BGdXq7pTQfuRtPexNnCnig/5UuMrrhI/M+qwJ8VBGH2V
      smtp_require_tls: true
    route:
      receiver: 'null'  
      group_by: ['team']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      routes:
        - receiver: 'gchat-and-email'
          matchers:
            - team="team-sre"
          continue: true
        - receiver: 'critical'
          matchers:
            - severity="critical"
          continue: true

        - match:
            severity: warning
            cluster: ecommerce-01-prd
            namespace: ecommerce
          receiver: 'ecommerce-01-prd-warning'
          continue: true

        - match:
            severity: warning
            cluster: ecommerce-01-prd
            namespace: ecommerce-item
          receiver: 'ecommerce-01-prd-warning'
          continue: true

        - match:
            severity: warning
            cluster: shd-ops-management
          receiver: 'shd-ops-management-warning'
          continue: true
        - match:
            alertname: InfoInhibitor
          receiver: null
          continue: false
        

    receivers:
      - name: 'gchat-and-email'
        email_configs:
          - to: 'devops-it@fravega.com.ar'
            send_resolved: true
        webhook_configs:
          - url: 'http://calert.observability:6000/dispatch'
            send_resolved: true
      - name: 'critical'
        webhook_configs:
          - url: 'http://calert.observability:6000/dispatch'
            send_resolved: true
      - name: 'ecommerce-01-prd-warning'
        webhook_configs:
          - url: 'http://calert.observability:6000/dispatch'
            send_resolved: true
      - name: 'shd-ops-management-warning'
        webhook_configs:
          - url: 'http://calert.observability:6000/dispatch'
            send_resolved: true
      - name: 'null'
