apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- tempo-stack.yaml

patches:
- path: ConfigMap-tempo-operator-manager-config.yaml

namespace: tempo-operator-system

