apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
